### ISSUE TITLE
I agree to the Terms of Use... button is hard to see

### ISSUE THREAD

**Issue by MaxAryus** [nerdynikhil/bloggy#13]
<img width="415" alt="Bildschirmfoto 2021-04-03 um 10 37 55" src="https://user-images.githubusercontent.com/60442357/113473254-c787af80-9468-11eb-83ee-5f8f124ee325.png">

**Comment by nerdynikhil** [comment]
Thanks @MaxAryus. You can work on it.

**Comment by MaxAryus** [comment]
Awsome, I am already working :D

**Comment by MaxAryus** [comment]
It is finished, forgot to open a separate pull request, sorry.
You can prove it at signup.dart line 220 to 240.

So I will close the issue.

**Comment by nerdynikhil** [comment]
@MaxAryus No issues.
